// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"CGMZ_Core","status":true,"description":"Core CGMZ Plugin, should be placed above all other CGMZ Plugins.","parameters":{"Check for Updates":"true","Dev Tools on Start":"false","Show FPS Counter":"false","Fullscreen":"false","Simulate Production Env":"false","Force Locale":"","Fallback Locale":"en-US"}},
{"name":"CGMZ_ExitToDesktop","status":true,"description":"Adds options to close the game window (exit to desktop)","parameters":{"Command Name":"Exit Game","Hide in Browser":"true","Hide in Title":"false","Hide in Game End":"false","Hide in Game Over":"false"}}
];
